use super::*;
use anyhow::{Context, Result, bail};
use std::collections::BTreeSet;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Create a temp directory only its owner can enter, for the import trees that hold design data.
///
/// `tempfile` gives temp *files* mode 0600 but leaves temp *directories* at the process umask, which
/// is 0755 by default. The KiCad source copies import stages for the CLI carry reference designators,
/// MPNs, net names, and absolute paths that disclose the username and layout, and they sit in a shared
/// directory, so they are created 0700 instead. Non-unix keeps the platform default.
pub(super) fn private_tempdir(prefix: &str) -> std::io::Result<tempfile::TempDir> {
    let mut builder = tempfile::Builder::new();
    builder.prefix(prefix);
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        builder.permissions(fs::Permissions::from_mode(0o700));
    }
    builder.tempdir()
}

/// Writes the import output directly into its destination directory.
///
/// Import is a one-way migration that converts a KiCad design into Zener sources. It only ever *adds*
/// files, so it needs no staging tree and no commit phase: a path that already exists is left alone
/// and reported, a path that does not is created. That is the whole no-overwrite rule.
///
/// `--force` additionally replaces what *this run* generates. Every content write goes through a
/// temp-file-and-rename, so a crash can leave an orphaned temp file but never a half-written source.
/// A failure mid-run therefore leaves the destination with some generated files and every
/// pre-existing file untouched; deleting the output directory and re-running is the recovery.
pub(super) struct ImportWriter {
    root: PathBuf,
    force: bool,
    /// Destination-relative paths this run created or replaced.
    ///
    /// This is tracked rather than inferred, because it is the only thing that distinguishes "import
    /// generated this, so the registry-fallback retry may rewrite it" from "this was already here, so
    /// nothing may touch it". Comparing bytes cannot tell those apart.
    written: BTreeSet<PathBuf>,
    /// Paths that already existed, so the generated version was discarded.
    kept: BTreeSet<PathBuf>,
    /// Packages whose existing content won, so nothing more may be written into them.
    ///
    /// A collision on *any* file inside a `components/<X>` / `modules/<X>` package keeps the whole
    /// package: pairing an authored `.zen` with a freshly generated symbol beside it would produce an
    /// incoherent package. A package whose files all regenerate identically never lands here — nothing
    /// was discarded, so there is nothing to keep.
    kept_packages: BTreeSet<PathBuf>,
}

impl ImportWriter {
    pub(super) fn new(root: &Path, board_name: &str, force: bool) -> Result<Self> {
        if let Some(warning) = paths::declared_board_mismatch_warning(root, board_name) {
            eprintln!("{warning}");
        }
        create_dir_checked(root, root)?;
        // Guarded per file inside, so a destination that already has `pcb.toml` keeps it and still
        // gains the `.gitignore` that keeps `.pcb/` out of `git status`.
        crate::new::write_board_scaffolding(root, board_name)?;

        Ok(Self {
            root: root.to_path_buf(),
            force,
            written: BTreeSet::new(),
            kept: BTreeSet::new(),
            kept_packages: BTreeSet::new(),
        })
    }

    pub(super) fn root(&self) -> &Path {
        &self.root
    }

    /// The destination-relative paths whose generated version was discarded in favour of what was
    /// already there.
    pub(super) fn kept_paths(&self) -> Vec<PathBuf> {
        self.kept.iter().cloned().collect()
    }

    /// Write generated bytes to `path`, unless something is already there.
    pub(super) fn write(&mut self, path: &Path, contents: &[u8]) -> Result<()> {
        self.write_with(path, |_| Ok(contents.to_vec()))
    }

    /// Write a generated `.zen`, formatted, unless something is already there.
    ///
    /// Formatting happens before the write decision: the decision compares the bytes that would land
    /// against the bytes already there, and for a `.zen` those are the *formatted* bytes.
    pub(super) fn write_zen(&mut self, path: &Path, content: &str) -> Result<()> {
        self.write_with(path, |parent| {
            crate::codegen::zen::format_zen(parent, content)
        })
    }

    /// Copy a referenced source file (a footprint, a KiCad project or board) into the output.
    pub(super) fn copy(&mut self, source: &Path, path: &Path) -> Result<()> {
        let contents =
            fs::read(source).with_context(|| format!("Failed to read {}", source.display()))?;
        self.write(path, &contents)
    }

    /// Copy a source directory tree into the output, one policy-checked file at a time.
    ///
    /// `skip` receives each path relative to `source` and drops it. Symlinks are refused rather than
    /// followed or recreated: a copied link could point anywhere, including outside the output.
    pub(super) fn copy_tree(
        &mut self,
        source: &Path,
        path: &Path,
        skip: &dyn Fn(&Path) -> bool,
    ) -> Result<()> {
        self.copy_tree_from(source, path, source, skip)
    }

    fn copy_tree_from(
        &mut self,
        current: &Path,
        path: &Path,
        source_root: &Path,
        skip: &dyn Fn(&Path) -> bool,
    ) -> Result<()> {
        for entry in fs::read_dir(current)
            .with_context(|| format!("Failed to read {}", current.display()))?
        {
            let entry = entry?;
            let entry_source = entry.path();
            let relative = entry_source
                .strip_prefix(source_root)
                .unwrap_or(&entry_source)
                .to_path_buf();
            if skip(&relative) {
                continue;
            }
            let metadata = fs::symlink_metadata(&entry_source)?;
            if metadata.file_type().is_symlink() {
                bail!(
                    "Copied source tree contains an unsupported symlink: {}",
                    entry_source.display()
                );
            }
            let destination = path.join(&relative);
            if metadata.is_dir() {
                self.copy_tree_from(&entry_source, path, source_root, skip)?;
            } else if metadata.is_file() {
                self.copy(&entry_source, &destination)?;
            }
        }
        Ok(())
    }

    /// Apply the write policy to `path`, then write what `produce` renders.
    ///
    /// The decision is the same for every kind of output, so it lives here once. In order: a path this
    /// run already wrote may be rewritten, because the registry-fallback retry regenerates. A path in a
    /// package that already existed is kept. An existing path is kept unless `--force`. A path whose
    /// generated bytes match what is already there is left alone *silently* — nothing was discarded, so
    /// reporting it as kept would warn about edits that were never lost.
    ///
    /// `produce` receives the destination's own directory, so a renderer needing scratch space keeps it
    /// on the same filesystem. It runs only once the path is known to be writable.
    fn write_with(
        &mut self,
        path: &Path,
        produce: impl FnOnce(&Path) -> Result<Vec<u8>>,
    ) -> Result<()> {
        let relative = self.relative(path)?;
        // `symlink_metadata`, so a symlinked destination counts as existing rather than being
        // followed. Under `--force` the rename replaces the link itself, never its target.
        let existing = fs::symlink_metadata(path).is_ok();
        let parent = path
            .parent()
            .map(Path::to_path_buf)
            .with_context(|| format!("Output path has no parent: {}", path.display()))?;

        let package = package_root(&relative);

        if !self.written.contains(&relative) {
            if package
                .as_ref()
                .is_some_and(|package| self.kept_packages.contains(package))
            {
                self.kept.insert(relative);
                return Ok(());
            }
            if existing && !self.force {
                // Render it anyway: only bytes that *differ* mean a generated version was discarded.
                create_dir_checked(&parent, &self.root)?;
                let contents = produce(&parent)?;
                if fs::read(path).ok().as_deref() == Some(contents.as_slice()) {
                    return Ok(());
                }
                if let Some(package) = package {
                    self.keep_package(&package)?;
                }
                self.kept.insert(relative);
                return Ok(());
            }
        }

        create_dir_checked(&parent, &self.root)?;
        let contents = produce(&parent)?;
        write_atomic(path, &contents)?;
        self.written.insert(relative);
        Ok(())
    }

    /// Discard everything this run generated under the package roots, so the registry-fallback retry
    /// regenerates from a clean slate.
    ///
    /// Bounded by `written`, so it removes only what import itself produced. The previous
    /// implementation deleted `components/` and `modules/` wholesale and then restored the
    /// destination's own files from a snapshot; with nothing staged there is nothing to restore,
    /// because a pre-existing file was never overwritten in the first place.
    ///
    /// The *reported* keeps in this scope are dropped along with the files, because the retry decides
    /// them again. Leaving them made `kept_paths` the union of both passes, so a file the first pass
    /// kept could still be reported after the retry discarded the substitution that produced its path
    /// — warning that edits were not reflected for a file the final import never tried to write.
    pub(super) fn discard_generated(&mut self, board_zen: &Path) -> Result<()> {
        let board_zen_rel = self.relative(board_zen)?;
        let discard = self
            .written
            .iter()
            .filter(|relative| is_regenerated(relative, &board_zen_rel))
            .cloned()
            .collect::<Vec<_>>();

        let mut discarded_dirs = BTreeSet::new();
        for relative in discard {
            let path = self.root.join(&relative);
            if let Err(error) = fs::remove_file(&path)
                && error.kind() != std::io::ErrorKind::NotFound
            {
                return Err(error)
                    .with_context(|| format!("Failed to discard generated {}", path.display()));
            }
            // Every directory between the generated root and the file is a candidate for removal.
            let mut parent = relative.parent();
            while let Some(dir) = parent.filter(|dir| !dir.as_os_str().is_empty()) {
                discarded_dirs.insert(dir.to_path_buf());
                parent = dir.parent();
            }
            self.written.remove(&relative);
        }
        // The directories those files were the only occupants of go too. Import's contract is that it
        // only ever *adds*, so leaving empty `components/<part>/` shells behind after a retry
        // contradicts it. `remove_dir` refuses a non-empty directory, so this can never take anything
        // the user owns; deepest first, so a package directory empties before its parent is tried.
        let mut vacated = discarded_dirs.into_iter().collect::<Vec<_>>();
        vacated.sort_by_key(|path| std::cmp::Reverse(path.components().count()));
        for relative in vacated {
            let _ = fs::remove_dir(self.root.join(relative));
        }

        // Scoped, not cleared: `layout/` and the source archive are written before generation and the
        // retry never revisits them, so a keep recorded for one of those is already final.
        self.kept
            .retain(|relative| !is_regenerated(relative, &board_zen_rel));
        // Packages kept in favour of their existing content stay kept: the retry must not write into
        // them either, and its own write attempt records the keep again.
        Ok(())
    }

    fn relative(&self, path: &Path) -> Result<PathBuf> {
        path.strip_prefix(&self.root)
            .map(Path::to_path_buf)
            .with_context(|| {
                format!(
                    "Import tried to write outside its output directory {}: {}",
                    self.root.display(),
                    path.display()
                )
            })
    }

    /// Hand `package` back to its existing content, undoing what this run already put in it.
    ///
    /// A collision is discovered file by file, so files this run generated earlier in the same package
    /// may already be on disk. Only paths in `written` are removed, and a path lands there only when it
    /// did not exist before, so nothing the user owns can be deleted here. They are reported as kept,
    /// because a consumer asking what did not get refreshed wants to hear about them.
    fn keep_package(&mut self, package: &Path) -> Result<()> {
        let generated = self
            .written
            .iter()
            .filter(|relative| relative.starts_with(package))
            .cloned()
            .collect::<Vec<_>>();
        for relative in generated {
            let path = self.root.join(&relative);
            fs::remove_file(&path).with_context(|| {
                format!(
                    "Failed to revert generated {} while keeping the existing package",
                    path.display()
                )
            })?;
            self.written.remove(&relative);
            self.kept.insert(relative);
        }
        self.kept_packages.insert(package.to_path_buf());
        Ok(())
    }
}

/// Whether `relative` is something generation produces on every pass, and which the
/// registry-fallback retry therefore decides again from scratch.
///
/// Shared by the two halves of [`ImportWriter::discard_generated`] so the files it removes and the
/// keeps it drops cannot come to describe different sets.
fn is_regenerated(relative: &Path, board_zen_rel: &Path) -> bool {
    relative == board_zen_rel
        || GENERATED_PACKAGE_ROOTS
            .iter()
            .any(|root| relative.starts_with(root))
}

/// The top-level directories generation owns. A package inside one is the unit of reuse, and the
/// registry-fallback retry clears what it generated under them.
const GENERATED_PACKAGE_ROOTS: [&str; 2] = ["components", "modules"];

/// The package a destination-relative path belongs to, if any.
///
/// A package is the directory the file sits in, at whatever depth that is: `components/<part>`,
/// `components/<manufacturer>/<part>`, or `components/registry/<hash>/<package>`. The keep rule exists
/// to stop an authored `.zen` being paired with a freshly generated symbol *beside it*, so the unit is
/// the containing directory.
///
/// Taking a fixed second path segment instead made the *manufacturer* directory the unit. A collision
/// in one part then kept every sibling part under that manufacturer — Meridian has seven packages
/// under `components/JST` — and [`ImportWriter::keep_package`] would delete the files this run had
/// already written for the others.
///
/// A file directly under a generated root belongs to no package and is judged on its own.
fn package_root(relative: &Path) -> Option<PathBuf> {
    let parent = relative.parent()?;
    let mut components = parent.components();
    let top = components.next()?;
    if !GENERATED_PACKAGE_ROOTS.contains(&top.as_os_str().to_str()?) {
        return None;
    }
    components.next()?;
    Some(parent.to_path_buf())
}

/// Render a path list for a user-facing message. Shared so every such list uses one separator.
pub(super) fn join_paths(paths: &[PathBuf]) -> String {
    paths
        .iter()
        .map(|path| path.display().to_string())
        .collect::<Vec<_>>()
        .join(", ")
}

/// Create `path` and its ancestors, refusing to follow a symlink standing in for a directory.
///
/// `create_dir_all` alone would happily resolve a symlinked ancestor and write the output somewhere
/// else entirely. Only ancestors at or below `root` are checked: the path *to* the output directory is
/// the user's own and may legitimately run through symlinks (`/var` is one on macOS). Only existing
/// entries are checked; anything import creates itself is a real directory.
fn create_dir_checked(path: &Path, root: &Path) -> Result<()> {
    let checked = path
        .ancestors()
        .take_while(|ancestor| ancestor.starts_with(root))
        .collect::<Vec<_>>();
    for ancestor in checked.into_iter().rev() {
        let Ok(metadata) = fs::symlink_metadata(ancestor) else {
            continue;
        };
        if metadata.file_type().is_symlink() {
            bail!(
                "Import output path resolves through a symlink: {}",
                ancestor.display()
            );
        }
        if !metadata.is_dir() {
            bail!(
                "Expected output directory, found file: {}",
                ancestor.display()
            );
        }
    }
    fs::create_dir_all(path)
        .with_context(|| format!("Failed to create output directory {}", path.display()))
}

/// Write `contents` to `destination` without ever leaving it truncated.
///
/// The bytes go to a temp file in the destination's own directory — `fs::rename` is only atomic
/// within one filesystem — and are renamed over it, preserving the destination's permissions when it
/// already exists. A crash, signal, or full disk can then only leave a temp file behind. Every error
/// path drops the `NamedTempFile`, which removes it.
///
/// One consequence of renaming: a destination that was hardlinked elsewhere is no longer updated
/// through its other links. Crash safety is worth more here than preserving a hardlink into
/// generated output.
fn write_atomic(destination: &Path, contents: &[u8]) -> Result<()> {
    let failed = || format!("Failed to write {}", destination.display());
    let parent = destination
        .parent()
        .with_context(|| format!("Output path has no parent: {}", destination.display()))?;
    let mut temp = tempfile::Builder::new()
        .prefix(".pcb-import-write-")
        .tempfile_in(parent)
        .with_context(failed)?;
    temp.write_all(contents).with_context(failed)?;
    if let Ok(metadata) = fs::metadata(destination) {
        temp.as_file()
            .set_permissions(metadata.permissions())
            .with_context(failed)?;
    }
    temp.as_file().sync_all().with_context(failed)?;
    temp.persist(destination)
        .map_err(|error| error.error)
        .with_context(failed)?;
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;

    const BOARD_MANIFEST: &str = "[workspace]\n[board]\nname='B'\npath='B.zen'\n";

    fn write_board_manifest(root: &Path) {
        fs::create_dir_all(root).unwrap();
        fs::write(root.join("pcb.toml"), BOARD_MANIFEST).unwrap();
    }

    /// A writer over a fresh output directory that already holds a board manifest.
    fn new_writer(force: bool) -> (tempfile::TempDir, ImportWriter) {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("board");
        write_board_manifest(&root);
        let writer = ImportWriter::new(&root, "B", force).unwrap();
        (temp, writer)
    }

    /// The write policy: add what is new, keep what differs, say nothing when the result is identical,
    /// and replace only under `--force`.
    ///
    /// This is the guarantee the whole in-place design rests on — import never destroys work the user
    /// or an agent did in the output directory.
    #[test]
    fn the_write_policy() {
        let (temp, mut writer) = new_writer(false);
        let root = temp.path().join("board");
        fs::write(root.join("authored.zen"), "authored").unwrap();
        fs::write(root.join("same.zen"), "identical").unwrap();

        writer
            .write(&root.join("authored.zen"), b"generated")
            .unwrap();
        writer.write(&root.join("same.zen"), b"identical").unwrap();
        writer.write(&root.join("fresh.zen"), b"generated").unwrap();

        assert_eq!(
            fs::read_to_string(root.join("authored.zen")).unwrap(),
            "authored",
            "an existing file that differs is never overwritten"
        );
        assert_eq!(
            fs::read_to_string(root.join("fresh.zen")).unwrap(),
            "generated"
        );
        assert_eq!(
            writer.kept_paths(),
            vec![PathBuf::from("authored.zen")],
            "only the discarded generation is reported; an identical regeneration is silent"
        );
        // The scaffolding is written when absent and never rewritten.
        assert_eq!(
            fs::read_to_string(root.join("pcb.toml")).unwrap(),
            BOARD_MANIFEST
        );
        assert!(
            fs::read_to_string(root.join(".gitignore"))
                .unwrap()
                .contains(".pcb"),
            "the .gitignore that hides the build directory is added even beside an existing manifest"
        );

        // `--force` replaces what the run generates, and still not the manifest.
        let (temp, mut writer) = new_writer(true);
        let root = temp.path().join("board");
        fs::write(root.join("authored.zen"), "authored").unwrap();
        writer
            .write(&root.join("authored.zen"), b"generated")
            .unwrap();
        assert_eq!(
            fs::read_to_string(root.join("authored.zen")).unwrap(),
            "generated"
        );
        assert!(writer.kept_paths().is_empty());
        assert_eq!(
            fs::read_to_string(root.join("pcb.toml")).unwrap(),
            BOARD_MANIFEST
        );
    }

    /// A `components/<X>` package is the unit of reuse, at whatever depth it sits.
    ///
    /// Pairing an authored `.zen` with a freshly generated symbol beside it would produce an incoherent
    /// package, so a collision anywhere inside one keeps the whole thing — including files this run had
    /// already written into it. A *sibling* package is untouched: taking a fixed path segment instead
    /// made the manufacturer directory the unit, and Meridian has seven packages under `components/JST`.
    #[test]
    fn the_package_is_the_unit_of_reuse() {
        assert_eq!(
            package_root(Path::new("components/Part/Part.zen")),
            Some(PathBuf::from("components/Part"))
        );
        assert_eq!(
            package_root(Path::new("components/JST/SM04B/SM04B.zen")),
            Some(PathBuf::from("components/JST/SM04B")),
            "a manufacturer-scoped package is its own unit"
        );
        assert_eq!(
            package_root(Path::new("components/loose.txt")),
            None,
            "a file directly under a generated root is judged on its own"
        );

        let (temp, mut writer) = new_writer(false);
        let root = temp.path().join("board");
        let part = root.join("components/JST/PartA");
        let sibling = root.join("components/JST/PartB");
        fs::create_dir_all(&part).unwrap();
        fs::write(part.join("PartA.zen"), "authored").unwrap();

        // The sibling is generated first, then the collision surfaces in PartA.
        writer
            .write(&sibling.join("PartB.zen"), b"generated")
            .unwrap();
        writer
            .write(&part.join("PartA.kicad_sym"), b"generated symbol")
            .unwrap();
        writer
            .write(&part.join("PartA.zen"), b"generated zen")
            .unwrap();

        assert_eq!(
            fs::read_to_string(part.join("PartA.zen")).unwrap(),
            "authored"
        );
        assert!(
            !part.join("PartA.kicad_sym").exists(),
            "the symbol this run wrote into the colliding package is reverted with it"
        );
        assert_eq!(
            fs::read_to_string(sibling.join("PartB.zen")).unwrap(),
            "generated",
            "a sibling package under the same manufacturer survives"
        );
        assert_eq!(
            writer.kept_paths(),
            vec![
                PathBuf::from("components/JST/PartA/PartA.kicad_sym"),
                PathBuf::from("components/JST/PartA/PartA.zen"),
            ]
        );
    }

    /// The registry-fallback retry regenerates, so it must be able to undo its first pass — and only
    /// its first pass.
    #[test]
    fn discard_generated_undoes_this_run_and_nothing_else() {
        let (temp, mut writer) = new_writer(false);
        let root = temp.path().join("board");
        let board_zen = root.join("B.zen");
        let authored = root.join("components/Authored");
        fs::create_dir_all(&authored).unwrap();
        fs::write(authored.join("Authored.zen"), "authored").unwrap();
        let layout = root.join("layout/board.kicad_pcb");
        fs::create_dir_all(layout.parent().unwrap()).unwrap();
        fs::write(&layout, "authored layout").unwrap();

        writer.write(&board_zen, b"pass 1").unwrap();
        writer
            .write(&root.join("components/Gen/Gen.zen"), b"pass 1")
            .unwrap();
        writer
            .write(&authored.join("Authored.zen"), b"pass 1")
            .unwrap();
        writer.write(&layout, b"pass 1 layout").unwrap();

        writer.discard_generated(&board_zen).unwrap();

        assert!(!board_zen.exists(), "the generated board goes");
        assert!(
            !root.join("components/Gen").exists(),
            "and the directory it emptied, since import only ever adds"
        );
        assert_eq!(
            fs::read_to_string(authored.join("Authored.zen")).unwrap(),
            "authored",
            "a file import never wrote survives"
        );
        assert_eq!(
            writer.kept_paths(),
            vec![PathBuf::from("layout/board.kicad_pcb")],
            "keeps inside the regenerated scope are dropped for the retry to decide again; \
             `layout/` is written before generation and its keep is already final"
        );

        // The retry writes freely again, and re-records its own collisions.
        writer.write(&board_zen, b"pass 2").unwrap();
        writer
            .write(&authored.join("Authored.zen"), b"pass 2")
            .unwrap();
        assert_eq!(fs::read_to_string(&board_zen).unwrap(), "pass 2");
        assert_eq!(
            fs::read_to_string(authored.join("Authored.zen")).unwrap(),
            "authored"
        );
    }

    /// Import must not be tricked into writing outside the directory it was given, and must not follow
    /// a symlink to do it.
    #[cfg(unix)]
    #[test]
    fn writes_stay_inside_the_output_directory() {
        use std::os::unix::fs::symlink;

        let (temp, mut writer) = new_writer(false);
        let root = temp.path().join("board");
        let outside = temp.path().join("outside.txt");
        fs::write(&outside, "outside").unwrap();

        // A path outside the root is refused outright.
        let error = writer
            .write(&temp.path().join("elsewhere.zen"), b"generated")
            .expect_err("a path outside the output root must be refused");
        assert!(format!("{error:#}").contains("outside its output directory"));

        // A symlinked destination counts as existing, so its target is never written through.
        symlink(&outside, root.join("B.zen")).unwrap();
        writer.write(&root.join("B.zen"), b"generated").unwrap();
        assert_eq!(fs::read_to_string(&outside).unwrap(), "outside");

        // A symlink standing in for an output directory would redirect the whole write.
        let elsewhere = temp.path().join("elsewhere");
        fs::create_dir(&elsewhere).unwrap();
        symlink(&elsewhere, root.join("components")).unwrap();
        let error = writer
            .write(&root.join("components/Part/Part.zen"), b"generated")
            .expect_err("a symlinked output directory must be refused");
        assert!(format!("{error:#}").contains("resolves through a symlink"));
        assert!(!elsewhere.join("Part").exists());

        // Under `--force` the rename replaces the link itself, not its target.
        let (forced_temp, mut forced) = new_writer(true);
        let root = forced_temp.path().join("board");
        let outside = forced_temp.path().join("outside.txt");
        fs::write(&outside, "outside").unwrap();
        symlink(&outside, root.join("B.zen")).unwrap();
        forced.write(&root.join("B.zen"), b"generated").unwrap();
        assert_eq!(fs::read_to_string(&outside).unwrap(), "outside");
        assert_eq!(fs::read_to_string(root.join("B.zen")).unwrap(), "generated");
    }

    /// Importing a second board into an existing board repository warns and leaves the manifest exactly
    /// as the user wrote it: `pcb.toml` holds one `[board]`, and import never rewrites a file it owns.
    #[test]
    fn a_different_declared_board_warns_and_leaves_the_manifest_alone() {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("board");
        fs::create_dir_all(&root).unwrap();
        let manifest = "[workspace]\n[board]\nname='Bar'\npath='Bar.zen'\n";
        fs::write(root.join("pcb.toml"), manifest).unwrap();

        assert!(paths::declared_board_mismatch_warning(&root, "Foo").is_some());
        let mut writer = ImportWriter::new(&root, "Foo", false).unwrap();
        writer.write(&root.join("Foo.zen"), b"generated").unwrap();

        assert_eq!(fs::read_to_string(root.join("pcb.toml")).unwrap(), manifest);
        assert_eq!(
            fs::read_to_string(root.join("Foo.zen")).unwrap(),
            "generated"
        );
    }
}
