[workspace]
name = "pcb"
pcb-version = "0.3"
members = [
    "stdlib/*",
    "examples/*",
]

[dependencies]
"gitlab.com/kicad/libraries/kicad-symbols" = "10.0.0"
"gitlab.com/kicad/libraries/kicad-footprints" = "10.0.0"
