use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let pkg_version = env::var("CARGO_PKG_VERSION").unwrap();

    let changelog_path = Path::new(&manifest_dir).join("../../CHANGELOG.md");
    println!("cargo:rerun-if-changed={}", changelog_path.display());

    let changelog = fs::read_to_string(&changelog_path)
        .unwrap_or_else(|_| "# Changelog\n\nNo changelog available.".to_string());

    let unreleased = extract_unreleased_release(&changelog)
        .map(|notes| format_changelog_markdown(&notes))
        .unwrap_or_else(|| "No unreleased notes available.".to_string());
    let (latest, is_unreleased) = extract_latest_release(&changelog);
    let latest = if is_unreleased {
        format!(
            "## v{}\n{}",
            pkg_version,
            format_changelog_markdown(&latest)
        )
    } else {
        format_changelog_markdown(&latest)
    };

    let output = format!(
        "// Auto-generated by build.rs\n\
         pub const CHANGELOG_MD: &str = {:?};\n\
         pub const UNRELEASED_RELEASE_NOTES: &str = {:?};\n\
         pub const LATEST_RELEASE_NOTES: &str = {:?};\n",
        format_changelog_markdown(&changelog),
        unreleased,
        latest
    );

    fs::write(Path::new(&out_dir).join("changelog.rs"), output)
        .expect("Failed to write changelog.rs");
}

fn extract_unreleased_release(content: &str) -> Option<String> {
    extract_release(content, true)
}

/// Extract the first release section with actual content.
fn extract_latest_release(content: &str) -> (String, bool) {
    let Some((release, is_unreleased)) = extract_first_nonempty_release(content) else {
        return ("No release notes available.".to_string(), false);
    };

    (release, is_unreleased)
}

fn extract_first_nonempty_release(content: &str) -> Option<(String, bool)> {
    let mut current = Vec::new();
    let mut current_is_unreleased = false;
    let mut in_section = false;
    let mut has_content = false;

    for line in content.lines() {
        if line.starts_with("## [") {
            if in_section && has_content {
                break;
            }
            current.clear();
            current_is_unreleased = line.contains("[Unreleased]");
            in_section = true;
            has_content = false;
            if !current_is_unreleased {
                current.push(line);
            }
            continue;
        }

        if in_section {
            let trimmed = line.trim();
            if trimmed.starts_with("- ") || trimmed.starts_with("* ") {
                has_content = true;
            }
            if !trimmed.is_empty() || !current.is_empty() {
                current.push(line);
            }
        }
    }

    while current.last().is_some_and(|s| s.trim().is_empty()) {
        current.pop();
    }

    has_content.then(|| (current.join("\n"), current_is_unreleased))
}

fn extract_release(content: &str, unreleased: bool) -> Option<String> {
    let mut result = Vec::new();
    let mut in_target_section = false;
    let mut has_content = false;

    for line in content.lines() {
        if line.starts_with("## [") {
            if in_target_section {
                break;
            }
            in_target_section = line.contains("[Unreleased]") == unreleased;
            if in_target_section {
                result.push(line);
            }
            continue;
        }

        if in_target_section {
            let trimmed = line.trim();
            if trimmed.starts_with("- ") || trimmed.starts_with("* ") {
                has_content = true;
            }
            if !trimmed.is_empty() || !result.is_empty() {
                result.push(line);
            }
        }
    }

    while result.last().is_some_and(|s| s.trim().is_empty()) {
        result.pop();
    }

    has_content.then(|| result.join("\n"))
}

/// Format changelog markdown while preserving internal spacing and fenced blocks.
fn format_changelog_markdown(content: &str) -> String {
    let mut result = Vec::new();
    let mut seen_content = false;
    let mut in_fence = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if !seen_content && trimmed.is_empty() {
            continue;
        }

        seen_content = true;

        if !in_fence {
            if let Some(header) = trimmed.strip_prefix("### ") {
                result.push(format!("**{}**", header));
            } else {
                result.push(line.to_string());
            }
        } else {
            result.push(line.to_string());
        }

        if trimmed.starts_with("```") {
            in_fence = !in_fence;
        }
    }

    while result.last().is_some_and(|line| line.trim().is_empty()) {
        result.pop();
    }

    result.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_unreleased_with_content() {
        let changelog = "## [Unreleased]\n### Added\n- Feature A\n## [0.3.22]\n- Old";
        let (result, is_unreleased) = extract_latest_release(changelog);
        assert!(is_unreleased);
        assert!(result.contains("Feature A"));
        assert!(!result.contains("Old"));
    }

    #[test]
    fn test_extract_versioned_when_unreleased_empty() {
        let changelog = "## [Unreleased]\n## [0.3.22]\n- Feature";
        let (result, is_unreleased) = extract_latest_release(changelog);
        assert!(!is_unreleased);
        assert!(result.contains("0.3.22"));
        assert!(result.contains("Feature"));
    }

    #[test]
    fn test_format_changelog_markdown() {
        let input = "## [0.3.22]\n\n### Added\n\n- Feature";
        assert_eq!(
            format_changelog_markdown(input),
            "## [0.3.22]\n\n**Added**\n\n- Feature"
        );
    }

    #[test]
    fn test_format_changelog_markdown_preserves_release_spacing() {
        let input = "## [Unreleased]\n\n### Migration Guide\n\nBefore:\n\n```python\nx = 1\n```\n\n### Added\n\n- Feature";
        assert_eq!(
            format_changelog_markdown(input),
            "## [Unreleased]\n\n**Migration Guide**\n\nBefore:\n\n```python\nx = 1\n```\n\n**Added**\n\n- Feature"
        );
    }

    #[test]
    fn test_format_changelog_markdown_does_not_rewrite_headers_inside_fences() {
        let input =
            "## [Unreleased]\n\n### Migration Guide\n\n```markdown\n### literal header\n```\n";
        assert_eq!(
            format_changelog_markdown(input),
            "## [Unreleased]\n\n**Migration Guide**\n\n```markdown\n### literal header\n```"
        );
    }

    #[test]
    fn test_extract_unreleased_release_with_content() {
        let changelog = "## [Unreleased]\n### Added\n- Feature A\n\n## [0.3.22]\n### Fixed\n- Old";
        let result = extract_unreleased_release(changelog).unwrap();
        assert!(result.contains("## [Unreleased]"));
        assert!(result.contains("Feature A"));
        assert!(!result.contains("0.3.22"));
    }

    #[test]
    fn test_extract_unreleased_release_without_content() {
        let changelog = "## [Unreleased]\n\n## [0.3.22]\n### Fixed\n- Old";
        assert_eq!(extract_unreleased_release(changelog), None);
    }
}
