[package]
name = "pcb"
version = "0.2.7"
edition = { workspace = true }
repository = { workspace = true }
description = "PCB toolchain shim and version manager"
homepage = { workspace = true }
authors = { workspace = true }
default-run = "pcb"

[[bin]]
name = "pcb"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
anstream = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
fslock = { workspace = true }
self-replace = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
ureq = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }
