[dependencies]
"gitlab.com/kicad/libraries/kicad-symbols" = "10.0.3"

[dependencies.indirect]
"gitlab.com/kicad/libraries/kicad-footprints@10" = "10.0.3"
"gitlab.com/kicad/libraries/kicad-packages3D@10" = "10.0.3"
