//! Development harness for inspecting board-array copper-balancing regions.
//!
//! This is intentionally an example target rather than a user-facing
//! `pcb ipc` command while the geometry contract is still being explored.

use pcb_ir::geom::GeometryAccuracy;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Parser;
use pcb_ipc2581_tools::commands::board_array::balance::{
    ArraySupportLayerSource, extract_array_support_layers,
};
use pcb_ipc2581_tools::geometry::{
    board_array_fabrication_profile_with_debug, board_array_vscore_lines, extract_layout,
};
use pcb_ipc2581_tools::ipc2581::{Ipc2581, Symbol, types::LayerFunction};
use pcb_ipc2581_tools::layers::copper_layers;
use pcb_ipc2581_tools::utils::file::load_ipc_file;
use pcb_ir::dialects::ipc::{
    BalancingRegionOptions, BoardArrayBalancingResult, BoardArraySupportDocument,
    BoardArraySupportLayerGeometry, DEFAULT_BALANCING_CLEARANCE_MM,
    DEFAULT_BALANCING_GAP_RADIUS_MM, DEFAULT_BALANCING_NUMERICAL_GUARD_MM,
    DEFAULT_BALANCING_REGULARIZATION_RADIUS_MM, board_array_balancing_region,
    inspect_board_array_balancing_input, root_panel_step,
};
use pcb_ir::geom::{BBox, ContourSet};
use serde::Serialize;

const SCHEMA: &str = "pcb-ir.board-array-balancing-debug.v9";
const DEFAULT_CHECK_AREA_TOLERANCE_MM2: f64 = 1e-4;
const SVG_PADDING_MM: f64 = 2.0;
const SVG_STROKE_MM: f64 = 0.12;

#[derive(Debug, Parser)]
#[command(
    about = "Derive and inspect the copper-balancing-safe region of an IPC-2581 board array",
    long_about = "Development harness that emits every intermediate planar region, a toggleable HTML/SVG overlay, per-layer support-feature views, and clearance-certificate checks."
)]
struct Args {
    /// Board-array IPC-2581 XML (plain or .zst).
    input: PathBuf,

    /// Directory to receive deterministic debug artifacts.
    #[arg(short, long)]
    output: PathBuf,

    /// Required Euclidean clearance from the panel boundary and every obstacle.
    #[arg(long, default_value_t = DEFAULT_BALANCING_CLEARANCE_MM)]
    clearance_mm: f64,

    /// Disk radius used to round filled-region corners and reject small regions or slivers.
    #[arg(long, default_value_t = DEFAULT_BALANCING_REGULARIZATION_RADIUS_MM)]
    regularization_radius_mm: f64,

    /// Rolling-disk radius for two-sided void gaps; minimum gap is twice this.
    #[arg(long, default_value_t = DEFAULT_BALANCING_GAP_RADIUS_MM)]
    gap_radius_mm: f64,

    /// Extra construction clearance reserved for polygonization/offset error.
    #[arg(long, default_value_t = DEFAULT_BALANCING_NUMERICAL_GUARD_MM)]
    numerical_guard_mm: f64,

    /// Maximum tolerated area for each set-theoretic validation violation.
    #[arg(long, default_value_t = DEFAULT_CHECK_AREA_TOLERANCE_MM2)]
    check_area_tolerance_mm2: f64,

    /// Reject inputs not generated by the A-series auto panelizer.
    #[arg(long)]
    require_a_series_auto: bool,

    /// Copper layer to inspect. Defaults to the first copper layer in the IPC.
    #[arg(long)]
    copper_layer: Option<String>,
}

#[derive(Debug)]
struct SupportLayer {
    name: String,
    function: String,
    source_feature_count: usize,
    feature_count: usize,
    source_path_count: usize,
    path_count: usize,
    excluded_documentation_path_count: usize,
    unpainted_path_count: usize,
    region: ContourSet,
}

#[derive(Debug)]
struct Regions {
    panel_outer: ContourSet,
    board_footprints: ContourSet,
    material_removal: ContourSet,
    support_features: ContourSet,
    raw_obstacles: ContourSet,
    panel_keep_in: ContourSet,
    obstacle_keep_out: ContourSet,
    clearance_safe_region: ContourSet,
    opened_candidates: ContourSet,
    removed_by_opening: ContourSet,
    narrow_voids: ContourSet,
    removed_by_gap_regularization: ContourSet,
    removed_by_regularization: ContourSet,
    safe_region: ContourSet,
    undersized_final_components: ContourSet,
    clearance_certificate: ContourSet,
    safe_outside_clearance_region: ContourSet,
    regularization_violations: ContourSet,
    gap_violations: ContourSet,
    certificate_outside_panel: ContourSet,
    certificate_obstacle_overlap: ContourSet,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct DebugArtifact {
    schema: &'static str,
    passed: bool,
    input: String,
    copper_layer: String,
    nominal_clearance_mm: f64,
    regularization_radius_mm: f64,
    gap_radius_mm: f64,
    numerical_guard_mm: f64,
    construction_clearance_mm: f64,
    check_area_tolerance_mm2: f64,
    panelization: PanelizationJson,
    counts: CountsJson,
    coverage: CoverageJson,
    regularization: RegularizationJson,
    checks: ChecksJson,
    support_layers: Vec<SupportLayerJson>,
    regions: RegionsJson,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CountsJson {
    board_instances: usize,
    source_layers: usize,
    source_support_features: usize,
    support_features: usize,
    source_support_paths: usize,
    support_paths: usize,
    excluded_documentation_paths: usize,
    vscore_lines: usize,
    vscore_relief_entries: usize,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct PanelizationJson {
    mode: Option<String>,
    sheet: Option<String>,
    columns: Option<u32>,
    rows: Option<u32>,
}

impl PanelizationJson {
    fn from_xml(xml: &str) -> Self {
        Self {
            mode: generated_metadata_value(xml, "diode.panelize.mode"),
            sheet: generated_metadata_value(xml, "diode.panelize.sheet"),
            columns: generated_metadata_value(xml, "diode.panelize.columns")
                .and_then(|value| value.parse().ok()),
            rows: generated_metadata_value(xml, "diode.panelize.rows")
                .and_then(|value| value.parse().ok()),
        }
    }

    fn is_a_series_auto(&self) -> bool {
        matches!(self.mode.as_deref(), Some("auto" | "auto_sheet"))
            && matches!(self.sheet.as_deref(), Some("A7" | "A6" | "A5" | "A4"))
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CoverageJson {
    complete: bool,
    unpainted_support_paths: usize,
    note: &'static str,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct ChecksJson {
    passed: bool,
    safe_outside_clearance_region_area_mm2: f64,
    regularization_violation_area_mm2: f64,
    gap_violation_area_mm2: f64,
    certificate_outside_panel_area_mm2: f64,
    certificate_obstacle_overlap_area_mm2: f64,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct RegularizationJson {
    clearance_safe_area_mm2: f64,
    final_safe_area_mm2: f64,
    removed_area_mm2: f64,
    removed_by_opening_area_mm2: f64,
    narrow_void_area_mm2: f64,
    removed_by_gap_regularization_area_mm2: f64,
    retained_fraction: f64,
    clearance_safe_component_count: usize,
    opened_component_count: usize,
    final_component_count: usize,
    smallest_final_component_area_mm2: Option<f64>,
    minimum_final_component_bbox_span_mm: Option<f64>,
    undersized_final_component_count: usize,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct SupportLayerJson {
    name: String,
    function: String,
    source_feature_count: usize,
    feature_count: usize,
    source_path_count: usize,
    path_count: usize,
    excluded_documentation_path_count: usize,
    unpainted_path_count: usize,
    region: RegionJson,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct RegionsJson {
    panel_outer: RegionJson,
    board_footprints: RegionJson,
    material_removal: RegionJson,
    support_features: RegionJson,
    raw_obstacles: RegionJson,
    panel_keep_in: RegionJson,
    obstacle_keep_out: RegionJson,
    clearance_safe_region: RegionJson,
    opened_candidates: RegionJson,
    removed_by_opening: RegionJson,
    narrow_voids: RegionJson,
    removed_by_gap_regularization: RegionJson,
    removed_by_regularization: RegionJson,
    safe_region: RegionJson,
    undersized_final_components: RegionJson,
    clearance_certificate: RegionJson,
    safe_outside_clearance_region: RegionJson,
    regularization_violations: RegionJson,
    gap_violations: RegionJson,
    certificate_outside_panel: RegionJson,
    certificate_obstacle_overlap: RegionJson,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct RegionJson {
    area_mm2: f64,
    ring_count: usize,
    vertex_count: usize,
    bbox_mm: Option<BBoxJson>,
    rings_mm: Vec<Vec<[f64; 2]>>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct BBoxJson {
    min: [f64; 2],
    max: [f64; 2],
}

impl From<&ContourSet> for RegionJson {
    fn from(region: &ContourSet) -> Self {
        Self {
            area_mm2: region.area(),
            ring_count: region.rings.len(),
            vertex_count: region.rings.iter().map(Vec::len).sum(),
            bbox_mm: (!region.bbox.is_empty()).then_some(BBoxJson {
                min: [region.bbox.min.x, region.bbox.min.y],
                max: [region.bbox.max.x, region.bbox.max.y],
            }),
            rings_mm: region.rings.clone(),
        }
    }
}

fn component_areas(region: &ContourSet) -> Vec<f64> {
    region
        .connected_components()
        .into_iter()
        .map(|component| component.area())
        .collect()
}

fn main() -> Result<()> {
    let accuracy = GeometryAccuracy::default();

    let args = Args::parse();
    // The radius and clearance options are validated by
    // `board_array_balancing_region` itself.
    if !args.check_area_tolerance_mm2.is_finite() || args.check_area_tolerance_mm2 < 0.0 {
        bail!("--check-area-tolerance-mm2 must be a finite non-negative number");
    }

    let input = args
        .input
        .canonicalize()
        .with_context(|| format!("failed to resolve input {}", args.input.display()))?;
    let xml = load_ipc_file(&input)?;
    let panelization = PanelizationJson::from_xml(&xml);
    if args.require_a_series_auto && !panelization.is_a_series_auto() {
        bail!(
            "input is not an A-series auto-panelized array (mode {:?}, sheet {:?})",
            panelization.mode,
            panelization.sheet
        );
    }
    let ipc = Ipc2581::parse(&xml).context("failed to parse IPC-2581 input")?;
    let ecad = ipc.ecad().context("IPC-2581 file has no ECAD section")?;
    let copper_layers = copper_layers(ecad);
    let selected_copper = match &args.copper_layer {
        Some(requested) => copper_layers
            .iter()
            .find(|layer| ipc.resolve(layer.name) == requested)
            .with_context(|| format!("copper layer '{requested}' was not found"))?,
        None => copper_layers
            .first()
            .context("IPC-2581 file has no copper layers")?,
    };
    let selected_copper_name = ipc.resolve(selected_copper.name).to_string();
    let layout = extract_layout(&ipc).context("failed to extract IPC layout graph")?;
    if root_panel_step(&layout).is_none() {
        bail!("input is not a board array: the IPC root step is not a panel");
    }

    let score_lines = board_array_vscore_lines(&ipc, accuracy)
        .context("failed to extract board-array V-score lines")?;
    let (fabrication_profile, relief_debug) =
        board_array_fabrication_profile_with_debug(&ipc, &layout, &score_lines, accuracy)
            .context("failed to compose board-array fabrication profile")?;

    let support_sources = extract_array_support_layers(&ipc, accuracy)?;
    let collection = inspect_board_array_balancing_input(
        &layout,
        &fabrication_profile,
        &copper_layers,
        support_sources
            .iter()
            .map(|source| BoardArraySupportDocument::new(&source.document, source.policy)),
        accuracy,
    )
    .context("failed to collect board-array balancing inputs")?;
    let balancing_input = collection.input_for_layer(selected_copper.name);
    let options = BalancingRegionOptions {
        clearance_mm: args.clearance_mm,
        regularization_radius_mm: args.regularization_radius_mm,
        gap_radius_mm: args.gap_radius_mm,
        numerical_guard_mm: args.numerical_guard_mm,
    };
    let result = board_array_balancing_region(&balancing_input, options, accuracy)
        .context("failed to compute board-array balancing region")?;
    let construction_clearance_mm = options.construction_clearance_mm();
    let certificate_passed = result.certificate.passes(args.check_area_tolerance_mm2);
    let support_features = balancing_input.support_features;
    let panel_outer = collection.panel_outer;
    let board_footprints = collection.board_footprints;
    let material_removal = collection.material_removal;
    let board_instances = collection.board_instance_count;
    let support_geometry = collection.support_layers;
    let support_layers = support_sources
        .into_iter()
        .zip(support_geometry)
        .map(|(source, geometry)| support_layer(source, geometry, selected_copper.name))
        .collect::<Vec<_>>();
    let BoardArrayBalancingResult {
        safe_region,
        intermediates,
        certificate,
    } = result;
    let final_components = safe_region.connected_components();
    let undersized_final_components = final_components
        .iter()
        .filter(|component| {
            component
                .disk_erode(args.regularization_radius_mm, accuracy)
                .unwrap()
                .is_empty()
        })
        .cloned()
        .fold(
            ContourSet::empty(safe_region.tolerance),
            |undersized, component| undersized.union(&component),
        );
    let removed_by_regularization = intermediates
        .removed_by_opening
        .union(&intermediates.removed_by_gap_regularization);
    let narrow_voids = intermediates
        .opened_candidates
        .disk_gap_violations(args.gap_radius_mm, accuracy)
        .unwrap();
    let regions = Regions {
        panel_outer,
        board_footprints,
        material_removal,
        support_features,
        raw_obstacles: intermediates.raw_obstacles,
        panel_keep_in: intermediates.panel_keep_in,
        obstacle_keep_out: intermediates.obstacle_keep_out,
        clearance_safe_region: intermediates.clearance_safe_region,
        opened_candidates: intermediates.opened_candidates,
        removed_by_opening: intermediates.removed_by_opening,
        narrow_voids,
        removed_by_gap_regularization: intermediates.removed_by_gap_regularization,
        removed_by_regularization,
        safe_region,
        undersized_final_components,
        clearance_certificate: certificate.swept_safe_region,
        safe_outside_clearance_region: certificate.safe_outside_clearance_region,
        regularization_violations: certificate.regularization_violations,
        gap_violations: certificate.gap_violations,
        certificate_outside_panel: certificate.outside_panel,
        certificate_obstacle_overlap: certificate.obstacle_overlap,
    };

    let checks = ChecksJson {
        passed: certificate_passed,
        safe_outside_clearance_region_area_mm2: regions.safe_outside_clearance_region.area(),
        regularization_violation_area_mm2: regions.regularization_violations.area(),
        gap_violation_area_mm2: regions.gap_violations.area(),
        certificate_outside_panel_area_mm2: regions.certificate_outside_panel.area(),
        certificate_obstacle_overlap_area_mm2: regions.certificate_obstacle_overlap.area(),
    };
    let clearance_safe_component_areas = component_areas(&regions.clearance_safe_region);
    let opened_component_areas = component_areas(&regions.opened_candidates);
    let final_component_areas = final_components
        .iter()
        .map(ContourSet::area)
        .collect::<Vec<_>>();
    let minimum_final_component_bbox_span_mm = final_components
        .iter()
        .map(|component| component.bbox.width().min(component.bbox.height()))
        .reduce(f64::min);
    let clearance_safe_area_mm2 = regions.clearance_safe_region.area();
    let final_safe_area_mm2 = regions.safe_region.area();
    let regularization = RegularizationJson {
        clearance_safe_area_mm2,
        final_safe_area_mm2,
        removed_area_mm2: regions.removed_by_regularization.area(),
        removed_by_opening_area_mm2: regions.removed_by_opening.area(),
        narrow_void_area_mm2: regions.narrow_voids.area(),
        removed_by_gap_regularization_area_mm2: regions.removed_by_gap_regularization.area(),
        retained_fraction: if clearance_safe_area_mm2 > 0.0 {
            final_safe_area_mm2 / clearance_safe_area_mm2
        } else {
            1.0
        },
        clearance_safe_component_count: clearance_safe_component_areas.len(),
        opened_component_count: opened_component_areas.len(),
        final_component_count: final_component_areas.len(),
        smallest_final_component_area_mm2: final_component_areas.into_iter().reduce(f64::min),
        minimum_final_component_bbox_span_mm,
        undersized_final_component_count: regions
            .undersized_final_components
            .connected_components()
            .len(),
    };

    let unpainted_support_paths = support_layers
        .iter()
        .map(|layer| layer.unpainted_path_count)
        .sum::<usize>();
    let passed = checks.passed
        && unpainted_support_paths == 0
        && regularization.undersized_final_component_count == 0;
    let artifact = DebugArtifact {
        schema: SCHEMA,
        passed,
        input: input.display().to_string(),
        copper_layer: selected_copper_name,
        nominal_clearance_mm: args.clearance_mm,
        regularization_radius_mm: args.regularization_radius_mm,
        gap_radius_mm: args.gap_radius_mm,
        numerical_guard_mm: args.numerical_guard_mm,
        construction_clearance_mm,
        check_area_tolerance_mm2: args.check_area_tolerance_mm2,
        panelization,
        counts: CountsJson {
            board_instances,
            source_layers: support_layers.len(),
            source_support_features: support_layers
                .iter()
                .map(|layer| layer.source_feature_count)
                .sum(),
            support_features: support_layers.iter().map(|layer| layer.feature_count).sum(),
            source_support_paths: support_layers
                .iter()
                .map(|layer| layer.source_path_count)
                .sum(),
            support_paths: support_layers.iter().map(|layer| layer.path_count).sum(),
            excluded_documentation_paths: support_layers
                .iter()
                .map(|layer| layer.excluded_documentation_path_count)
                .sum(),
            vscore_lines: score_lines.len(),
            vscore_relief_entries: relief_debug.entries.len(),
        },
        coverage: CoverageJson {
            complete: unpainted_support_paths == 0,
            unpainted_support_paths,
            note: "Every painted ArraySupport path is assigned once from its IR feature span: exact copper and adjacent-surface geometry affect that copper layer, while through-stack or unresolved physical geometry affects all copper layers. Same-layer V-cut arrows and labels are excluded by the V_Cut process specification. Unpainted included paths have no defined physical envelope and are reported as incomplete coverage.",
        },
        regularization,
        checks,
        support_layers: support_layers
            .iter()
            .map(|layer| SupportLayerJson {
                name: layer.name.clone(),
                function: layer.function.clone(),
                source_feature_count: layer.source_feature_count,
                feature_count: layer.feature_count,
                source_path_count: layer.source_path_count,
                path_count: layer.path_count,
                excluded_documentation_path_count: layer.excluded_documentation_path_count,
                unpainted_path_count: layer.unpainted_path_count,
                region: RegionJson::from(&layer.region),
            })
            .collect(),
        regions: RegionsJson {
            panel_outer: RegionJson::from(&regions.panel_outer),
            board_footprints: RegionJson::from(&regions.board_footprints),
            material_removal: RegionJson::from(&regions.material_removal),
            support_features: RegionJson::from(&regions.support_features),
            raw_obstacles: RegionJson::from(&regions.raw_obstacles),
            panel_keep_in: RegionJson::from(&regions.panel_keep_in),
            obstacle_keep_out: RegionJson::from(&regions.obstacle_keep_out),
            clearance_safe_region: RegionJson::from(&regions.clearance_safe_region),
            opened_candidates: RegionJson::from(&regions.opened_candidates),
            removed_by_opening: RegionJson::from(&regions.removed_by_opening),
            narrow_voids: RegionJson::from(&regions.narrow_voids),
            removed_by_gap_regularization: RegionJson::from(&regions.removed_by_gap_regularization),
            removed_by_regularization: RegionJson::from(&regions.removed_by_regularization),
            safe_region: RegionJson::from(&regions.safe_region),
            undersized_final_components: RegionJson::from(&regions.undersized_final_components),
            clearance_certificate: RegionJson::from(&regions.clearance_certificate),
            safe_outside_clearance_region: RegionJson::from(&regions.safe_outside_clearance_region),
            regularization_violations: RegionJson::from(&regions.regularization_violations),
            gap_violations: RegionJson::from(&regions.gap_violations),
            certificate_outside_panel: RegionJson::from(&regions.certificate_outside_panel),
            certificate_obstacle_overlap: RegionJson::from(&regions.certificate_obstacle_overlap),
        },
    };

    write_artifacts(&args.output, &input, &regions, &support_layers, &artifact)?;

    println!("wrote {}", args.output.join("index.html").display());
    println!(
        "safe area: {:.3} mm² ({:.1}% of the {:.3} mm² panel)",
        regions.safe_region.area(),
        100.0 * regions.safe_region.area() / regions.panel_outer.area(),
        regions.panel_outer.area()
    );
    println!(
        "regularization: {:.3} mm region radius, {:.3} mm gap radius retained {:.3} / {:.3} mm² ({:.1}%, {} clearance-safe -> {} opened -> {} final components, {} undersized)",
        artifact.regularization_radius_mm,
        artifact.gap_radius_mm,
        artifact.regularization.final_safe_area_mm2,
        artifact.regularization.clearance_safe_area_mm2,
        100.0 * artifact.regularization.retained_fraction,
        artifact.regularization.clearance_safe_component_count,
        artifact.regularization.opened_component_count,
        artifact.regularization.final_component_count,
        artifact.regularization.undersized_final_component_count,
    );
    println!(
        "coverage: {} ({} unpainted support paths)",
        if artifact.coverage.complete {
            "complete"
        } else {
            "incomplete"
        },
        artifact.coverage.unpainted_support_paths
    );
    println!(
        "certificate: {} (outside clearance-safe region {:.6} mm², regularization violations {:.6} mm², void-gap violations {:.6} mm², outside panel {:.6} mm², obstacle overlap {:.6} mm²)",
        if artifact.checks.passed {
            "PASS"
        } else {
            "FAIL"
        },
        artifact.checks.safe_outside_clearance_region_area_mm2,
        artifact.checks.regularization_violation_area_mm2,
        artifact.checks.gap_violation_area_mm2,
        artifact.checks.certificate_outside_panel_area_mm2,
        artifact.checks.certificate_obstacle_overlap_area_mm2,
    );

    if !artifact.passed {
        bail!(
            "balancing-region validation failed; debug artifacts were written to {}",
            args.output.display()
        );
    }

    Ok(())
}

fn support_layer(
    source: ArraySupportLayerSource,
    geometry: BoardArraySupportLayerGeometry<Symbol>,
    copper_layer: Symbol,
) -> SupportLayer {
    SupportLayer {
        name: source.name,
        function: layer_function_name(source.layer_function),
        source_feature_count: geometry.source_feature_count,
        feature_count: geometry.feature_count,
        source_path_count: geometry.source_path_count,
        path_count: geometry.path_count,
        excluded_documentation_path_count: geometry.excluded_documentation_path_count,
        unpainted_path_count: geometry.unpainted_path_count,
        region: geometry.region_for_layer(copper_layer),
    }
}

fn layer_function_name(function: LayerFunction) -> String {
    format!("{function:?}")
}

fn generated_metadata_value(xml: &str, name: &str) -> Option<String> {
    let marker = format!("name=\"{name}\"");
    let start = xml.find(&marker).unwrap();
    let tag = &xml[start..start + xml[start..].find('>').unwrap()];
    let value_start = tag.find("value=\"").unwrap() + "value=\"".len();
    let value = &tag[value_start..];
    Some(value[..value.find('"').unwrap()].to_string())
}

fn write_artifacts(
    output: &Path,
    input: &Path,
    regions: &Regions,
    support_layers: &[SupportLayer],
    artifact: &DebugArtifact,
) -> Result<()> {
    fs::create_dir_all(output)
        .with_context(|| format!("failed to create output directory {}", output.display()))?;

    let title = format!(
        "{} · {} — {:.3} mm clearance, {:.3} mm region radius, {:.3} mm gap radius (+{:.3} mm geometry guard)",
        input
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("board array"),
        artifact.copper_layer,
        artifact.nominal_clearance_mm,
        artifact.regularization_radius_mm,
        artifact.gap_radius_mm,
        artifact.numerical_guard_mm
    );
    let overview = render_overview_svg(&title, regions);
    write_file(output.join("overview.svg"), &overview)?;

    let stages = [
        Stage {
            filename: "00-panel-outer.svg",
            title: "00 — raw panel outer region",
            region: &regions.panel_outer,
            fill: "#e2e8f0",
            stroke: "#0f172a",
        },
        Stage {
            filename: "10-board-footprints.svg",
            title: "10 — final board-instance footprints",
            region: &regions.board_footprints,
            fill: "#fb7185",
            stroke: "#be123c",
        },
        Stage {
            filename: "20-material-removal.svg",
            title: "20 — profile cutouts and generated relief material",
            region: &regions.material_removal,
            fill: "#fb923c",
            stroke: "#c2410c",
        },
        Stage {
            filename: "30-support-features.svg",
            title: "30 — ArraySupport feature footprints affecting this copper layer",
            region: &regions.support_features,
            fill: "#a78bfa",
            stroke: "#6d28d9",
        },
        Stage {
            filename: "40-raw-obstacles.svg",
            title: "40 — union of all raw obstacles",
            region: &regions.raw_obstacles,
            fill: "#f87171",
            stroke: "#b91c1c",
        },
        Stage {
            filename: "50-panel-keep-in.svg",
            title: "50 — panel outer region eroded by construction clearance",
            region: &regions.panel_keep_in,
            fill: "#67e8f9",
            stroke: "#0e7490",
        },
        Stage {
            filename: "60-obstacle-keep-out.svg",
            title: "60 — raw obstacles dilated by construction clearance",
            region: &regions.obstacle_keep_out,
            fill: "#fca5a5",
            stroke: "#dc2626",
        },
        Stage {
            filename: "70-clearance-safe-region.svg",
            title: "70 — clearance-safe region before regularization",
            region: &regions.clearance_safe_region,
            fill: "#fde68a",
            stroke: "#b45309",
        },
        Stage {
            filename: "75-opened-candidates.svg",
            title: "75 — disk opening before void-gap regularization",
            region: &regions.opened_candidates,
            fill: "#86efac",
            stroke: "#16a34a",
        },
        Stage {
            filename: "80-removed-by-opening.svg",
            title: "80 — sharp, narrow, and small geometry removed by disk opening",
            region: &regions.removed_by_opening,
            fill: "#fb923c",
            stroke: "#c2410c",
        },
        Stage {
            filename: "82-narrow-voids.svg",
            title: "82 — two-sided voids rejected by the rolling-disk test",
            region: &regions.narrow_voids,
            fill: "#22d3ee",
            stroke: "#0e7490",
        },
        Stage {
            filename: "85-removed-by-gap-regularization.svg",
            title: "85 — material trimmed to widen narrow void gaps",
            region: &regions.removed_by_gap_regularization,
            fill: "#f472b6",
            stroke: "#be185d",
        },
        Stage {
            filename: "90-safe-region.svg",
            title: "90 — final regularized balancing-safe region",
            region: &regions.safe_region,
            fill: "#4ade80",
            stroke: "#15803d",
        },
        Stage {
            filename: "100-clearance-certificate.svg",
            title: "100 — final safe region dilated by nominal clearance",
            region: &regions.clearance_certificate,
            fill: "#60a5fa",
            stroke: "#1d4ed8",
        },
        Stage {
            filename: "105-gap-violations.svg",
            title: "105 — two-sided void gaps narrower than the disk diameter",
            region: &regions.gap_violations,
            fill: "#c026d3",
            stroke: "#701a75",
        },
    ];
    for stage in &stages {
        write_file(
            output.join(stage.filename),
            &render_stage_svg(stage.title, &regions.panel_outer, stage),
        )?;
    }
    write_file(
        output.join("110-validation-violations.svg"),
        &render_validation_svg(
            "110 — regularization and clearance-certificate violations",
            regions,
        ),
    )?;

    let layer_dir = output.join("support-layers");
    fs::create_dir_all(&layer_dir).with_context(|| {
        format!(
            "failed to create support-layer directory {}",
            layer_dir.display()
        )
    })?;
    let mut support_files = Vec::new();
    for (index, layer) in support_layers
        .iter()
        .filter(|layer| !layer.region.is_empty() || layer.unpainted_path_count > 0)
        .enumerate()
    {
        let filename = format!("{index:02}-{}.svg", slug(&layer.name));
        let stage = Stage {
            filename: &filename,
            title: &layer.name,
            region: &layer.region,
            fill: "#a78bfa",
            stroke: "#6d28d9",
        };
        write_file(
            layer_dir.join(&filename),
            &render_stage_svg(&layer.name, &regions.panel_outer, &stage),
        )?;
        support_files.push(format!("support-layers/{filename}"));
    }

    let json = serde_json::to_string_pretty(artifact)
        .context("failed to serialize balancing-region debug data")?;
    write_file(output.join("regions.json"), &json)?;
    write_file(
        output.join("index.html"),
        &render_index_html(
            &title,
            &overview,
            regions,
            artifact,
            &stages,
            &support_files,
        ),
    )?;
    Ok(())
}

struct Stage<'a> {
    filename: &'a str,
    title: &'a str,
    region: &'a ContourSet,
    fill: &'a str,
    stroke: &'a str,
}

fn render_stage_svg(title: &str, panel: &ContourSet, stage: &Stage<'_>) -> String {
    let bbox = panel.bbox.union(stage.region.bbox);
    let mut svg = svg_start(title, bbox);
    write_region(
        &mut svg,
        "panel-context",
        panel,
        "fill='#f8fafc' stroke='#475569' fill-opacity='1'",
    );
    write_region(
        &mut svg,
        "stage",
        stage.region,
        &format!(
            "fill='{}' stroke='{}' fill-opacity='0.62'",
            stage.fill, stage.stroke
        ),
    );
    svg.push_str("  </g>\n</svg>\n");
    svg
}

fn render_validation_svg(title: &str, regions: &Regions) -> String {
    let bbox = regions
        .panel_outer
        .bbox
        .union(regions.safe_outside_clearance_region.bbox)
        .union(regions.undersized_final_components.bbox)
        .union(regions.regularization_violations.bbox)
        .union(regions.gap_violations.bbox)
        .union(regions.certificate_outside_panel.bbox)
        .union(regions.certificate_obstacle_overlap.bbox);
    let mut svg = svg_start(title, bbox);
    write_region(
        &mut svg,
        "panel-context",
        &regions.panel_outer,
        "fill='#f8fafc' stroke='#475569' fill-opacity='1'",
    );
    write_region(
        &mut svg,
        "safe-outside-clearance-region",
        &regions.safe_outside_clearance_region,
        "fill='#e11d48' stroke='#881337' fill-opacity='0.9'",
    );
    write_region(
        &mut svg,
        "undersized-final-components",
        &regions.undersized_final_components,
        "fill='#db2777' stroke='#831843' fill-opacity='0.9'",
    );
    write_region(
        &mut svg,
        "regularization-violations",
        &regions.regularization_violations,
        "fill='#7c3aed' stroke='#4c1d95' fill-opacity='0.9'",
    );
    write_region(
        &mut svg,
        "gap-violations",
        &regions.gap_violations,
        "fill='#c026d3' stroke='#701a75' fill-opacity='0.9'",
    );
    write_region(
        &mut svg,
        "certificate-outside-panel",
        &regions.certificate_outside_panel,
        "fill='#dc2626' stroke='#7f1d1d' fill-opacity='0.9'",
    );
    write_region(
        &mut svg,
        "certificate-obstacle-overlap",
        &regions.certificate_obstacle_overlap,
        "fill='#f59e0b' stroke='#92400e' fill-opacity='0.9'",
    );
    svg.push_str("  </g>\n</svg>\n");
    svg
}

fn render_overview_svg(title: &str, regions: &Regions) -> String {
    let bbox = regions
        .panel_outer
        .bbox
        .union(regions.clearance_certificate.bbox)
        .union(regions.certificate_outside_panel.bbox);
    let mut svg = svg_start(title, bbox);
    write_region(
        &mut svg,
        "panel-outer",
        &regions.panel_outer,
        "fill='#f8fafc' stroke='#0f172a' fill-opacity='1'",
    );
    write_region(
        &mut svg,
        "obstacle-keep-out",
        &regions.obstacle_keep_out,
        "fill='#fecaca' stroke='#ef4444' fill-opacity='0.62'",
    );
    write_region(
        &mut svg,
        "panel-keep-in",
        &regions.panel_keep_in,
        "fill='none' stroke='#0891b2' stroke-dasharray='0.6 0.5'",
    );
    write_region(
        &mut svg,
        "clearance-safe-region",
        &regions.clearance_safe_region,
        "fill='#fde68a' stroke='#b45309' fill-opacity='0.24'",
    );
    write_region(
        &mut svg,
        "opened-candidates",
        &regions.opened_candidates,
        "fill='#86efac' stroke='#16a34a' fill-opacity='0.24'",
    );
    write_region(
        &mut svg,
        "removed-by-opening",
        &regions.removed_by_opening,
        "fill='#fb923c' stroke='#c2410c' fill-opacity='0.82'",
    );
    write_region(
        &mut svg,
        "narrow-voids",
        &regions.narrow_voids,
        "fill='#22d3ee' stroke='#0e7490' fill-opacity='0.42'",
    );
    write_region(
        &mut svg,
        "removed-by-gap-regularization",
        &regions.removed_by_gap_regularization,
        "fill='#f472b6' stroke='#be185d' fill-opacity='0.88'",
    );
    write_region(
        &mut svg,
        "safe-region",
        &regions.safe_region,
        "fill='#4ade80' stroke='#15803d' fill-opacity='0.72'",
    );
    write_region(
        &mut svg,
        "board-footprints",
        &regions.board_footprints,
        "fill='#fb7185' stroke='#be123c' fill-opacity='0.28'",
    );
    write_region(
        &mut svg,
        "material-removal",
        &regions.material_removal,
        "fill='#fb923c' stroke='#c2410c' fill-opacity='0.72'",
    );
    write_region(
        &mut svg,
        "support-features",
        &regions.support_features,
        "fill='#a78bfa' stroke='#6d28d9' fill-opacity='0.78'",
    );
    write_region(
        &mut svg,
        "clearance-certificate",
        &regions.clearance_certificate,
        "fill='none' stroke='#2563eb' stroke-dasharray='0.4 0.4' stroke-opacity='0.72'",
    );
    write_region(
        &mut svg,
        "undersized-final-components",
        &regions.undersized_final_components,
        "fill='#db2777' stroke='#831843' fill-opacity='0.95'",
    );
    write_region(
        &mut svg,
        "regularization-violations",
        &regions.regularization_violations,
        "fill='#7c3aed' stroke='#4c1d95' fill-opacity='0.95'",
    );
    write_region(
        &mut svg,
        "gap-violations",
        &regions.gap_violations,
        "fill='#c026d3' stroke='#701a75' fill-opacity='0.95'",
    );
    write_region(
        &mut svg,
        "safe-outside-clearance-region",
        &regions.safe_outside_clearance_region,
        "fill='#e11d48' stroke='#881337' fill-opacity='0.95'",
    );
    write_region(
        &mut svg,
        "certificate-outside-panel",
        &regions.certificate_outside_panel,
        "fill='#dc2626' stroke='#7f1d1d' fill-opacity='0.95'",
    );
    write_region(
        &mut svg,
        "certificate-obstacle-overlap",
        &regions.certificate_obstacle_overlap,
        "fill='#f59e0b' stroke='#92400e' fill-opacity='0.95'",
    );
    svg.push_str("  </g>\n</svg>\n");
    svg
}

fn svg_start(title: &str, bbox: BBox) -> String {
    let bbox = if bbox.is_empty() {
        BBox::new(
            pcb_ir::geom::Point::new(0.0, 0.0),
            pcb_ir::geom::Point::new(1.0, 1.0),
        )
    } else {
        bbox
    };
    let min_x = bbox.min.x - SVG_PADDING_MM;
    let min_y = -(bbox.max.y + SVG_PADDING_MM);
    let width = bbox.width() + 2.0 * SVG_PADDING_MM;
    let height = bbox.height() + 2.0 * SVG_PADDING_MM;
    let mut svg = String::new();
    writeln!(
        svg,
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='{} {} {} {}' role='img'>",
        num(min_x),
        num(min_y),
        num(width),
        num(height)
    )
    .unwrap();
    writeln!(svg, "  <title>{}</title>", escape_html(title)).unwrap();
    writeln!(
        svg,
        "  <rect x='{}' y='{}' width='{}' height='{}' fill='#ffffff'/>",
        num(min_x),
        num(min_y),
        num(width),
        num(height)
    )
    .unwrap();
    writeln!(
        svg,
        "  <g transform='scale(1 -1)' stroke-width='{}' stroke-linejoin='round' stroke-linecap='round'>",
        num(SVG_STROKE_MM)
    )
    .unwrap();
    svg
}

fn write_region(svg: &mut String, id: &str, region: &ContourSet, attributes: &str) {
    let Some(path) = region_path_data(region) else {
        writeln!(svg, "    <g id='{id}' data-empty='true'/>").unwrap();
        return;
    };
    writeln!(
        svg,
        "    <path id='{id}' d='{path}' {attributes} fill-rule='nonzero'/>"
    )
    .unwrap();
}

fn region_path_data(region: &ContourSet) -> Option<String> {
    let mut data = String::new();
    for ring in &region.rings {
        let Some(([x, y], rest)) = ring.split_first() else {
            continue;
        };
        if !data.is_empty() {
            data.push(' ');
        }
        write!(data, "M{} {}", num(*x), num(*y)).unwrap();
        for [x, y] in rest {
            write!(data, " L{} {}", num(*x), num(*y)).unwrap();
        }
        data.push_str(" Z");
    }
    (!data.is_empty()).then_some(data)
}

fn render_index_html(
    title: &str,
    overview: &str,
    regions: &Regions,
    artifact: &DebugArtifact,
    stages: &[Stage<'_>],
    support_files: &[String],
) -> String {
    let mut stage_links = String::new();
    for stage in stages {
        writeln!(
            stage_links,
            "<li><a href='{}'>{}</a></li>",
            escape_html(stage.filename),
            escape_html(stage.title)
        )
        .unwrap();
    }
    stage_links.push_str(
        "<li><a href='110-validation-violations.svg'>110 — regularization and clearance-certificate violations</a></li>",
    );

    let mut support_links = String::new();
    if support_files.is_empty() {
        support_links.push_str("<li>No non-empty support layers.</li>");
    } else {
        for file in support_files {
            writeln!(
                support_links,
                "<li><a href='{}'>{}</a></li>",
                escape_html(file),
                escape_html(file)
            )
            .unwrap();
        }
    }

    let checked = |value: bool| if value { " checked" } else { "" };
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{ color-scheme: light; font-family: ui-sans-serif, system-ui, sans-serif; }}
    body {{ margin: 0; background: #f1f5f9; color: #0f172a; }}
    main {{ max-width: 1500px; margin: 0 auto; padding: 24px; }}
    h1 {{ font-size: 1.25rem; margin: 0 0 8px; }}
    .subtle {{ color: #475569; margin: 0 0 18px; }}
    .layout {{ display: grid; grid-template-columns: minmax(220px, 300px) minmax(0, 1fr); gap: 18px; }}
    .panel {{ background: white; border: 1px solid #cbd5e1; border-radius: 10px; padding: 14px; box-shadow: 0 1px 3px #0f172a12; }}
    .viewer {{ min-width: 0; }}
    .viewer svg {{ display: block; width: 100%; height: min(76vh, 900px); }}
    fieldset {{ border: 0; padding: 0; margin: 0 0 16px; }}
    legend {{ font-weight: 700; margin-bottom: 8px; }}
    label {{ display: flex; align-items: center; gap: 8px; margin: 7px 0; font-size: 0.9rem; }}
    .swatch {{ width: 12px; height: 12px; border-radius: 3px; display: inline-block; }}
    dl {{ display: grid; grid-template-columns: 1fr auto; gap: 6px 12px; font-size: 0.88rem; }}
    dt {{ color: #475569; }} dd {{ margin: 0; font-variant-numeric: tabular-nums; }}
    .pass {{ color: #15803d; font-weight: 700; }} .fail {{ color: #b91c1c; font-weight: 700; }}
    details {{ margin-top: 14px; }} ul {{ padding-left: 20px; }} a {{ color: #1d4ed8; }}
    code {{ font-family: ui-monospace, SFMono-Regular, monospace; font-size: 0.82rem; }}
    @media (max-width: 800px) {{ .layout {{ grid-template-columns: 1fr; }} }}
  </style>
</head>
<body>
<main>
  <h1>{title}</h1>
  <p class="subtle">All coordinates and areas come from the serialized <a href="regions.json">regions.json</a>. Toggle groups to inspect the exact geometry used by the computation.</p>
  <div class="layout">
    <aside class="panel">
      <fieldset>
        <legend>Geometry</legend>
        <label><input type="checkbox" data-layer="panel-outer"{panel_outer}><span class="swatch" style="background:#e2e8f0"></span>panel outer</label>
        <label><input type="checkbox" data-layer="panel-keep-in"{panel_keep_in}><span class="swatch" style="background:#22d3ee"></span>clearance keep-in</label>
        <label><input type="checkbox" data-layer="obstacle-keep-out"{obstacle_keep_out}><span class="swatch" style="background:#fecaca"></span>clearance keep-out</label>
        <label><input type="checkbox" data-layer="clearance-safe-region"{clearance_safe_region}><span class="swatch" style="background:#fde68a"></span>clearance-safe region</label>
        <label><input type="checkbox" data-layer="opened-candidates"{opened_candidates}><span class="swatch" style="background:#86efac"></span>disk-opened candidates</label>
        <label><input type="checkbox" data-layer="removed-by-opening"{removed_by_opening}><span class="swatch" style="background:#fb923c"></span>discarded by opening</label>
        <label><input type="checkbox" data-layer="narrow-voids"{narrow_voids}><span class="swatch" style="background:#22d3ee"></span>narrow two-sided voids</label>
        <label><input type="checkbox" data-layer="removed-by-gap-regularization"{removed_by_gap_regularization}><span class="swatch" style="background:#f472b6"></span>trimmed to widen gaps</label>
        <label><input type="checkbox" data-layer="safe-region"{safe_region}><span class="swatch" style="background:#4ade80"></span>regularized safe region</label>
        <label><input type="checkbox" data-layer="board-footprints"{board_footprints}><span class="swatch" style="background:#fb7185"></span>board footprints</label>
        <label><input type="checkbox" data-layer="material-removal"{material_removal}><span class="swatch" style="background:#fb923c"></span>material removal</label>
        <label><input type="checkbox" data-layer="support-features"{support_features}><span class="swatch" style="background:#a78bfa"></span>support features</label>
        <label><input type="checkbox" data-layer="clearance-certificate"{certificate}><span class="swatch" style="background:#60a5fa"></span>clearance certificate</label>
        <label><input type="checkbox" data-layer="undersized-final-components"{violations}><span class="swatch" style="background:#db2777"></span>undersized-final violation</label>
        <label><input type="checkbox" data-layer="regularization-violations"{violations}><span class="swatch" style="background:#7c3aed"></span>regularization violation</label>
        <label><input type="checkbox" data-layer="gap-violations"{violations}><span class="swatch" style="background:#c026d3"></span>void-gap violation</label>
        <label><input type="checkbox" data-layer="safe-outside-clearance-region"{violations}><span class="swatch" style="background:#e11d48"></span>outside-clearance violation</label>
        <label><input type="checkbox" data-layer="certificate-outside-panel"{violations}><span class="swatch" style="background:#dc2626"></span>outside-panel violation</label>
        <label><input type="checkbox" data-layer="certificate-obstacle-overlap"{violations}><span class="swatch" style="background:#f59e0b"></span>obstacle-overlap violation</label>
      </fieldset>
      <dl>
        <dt>Panel area</dt><dd>{panel_area:.3} mm²</dd>
        <dt>Copper layer</dt><dd>{copper_layer}</dd>
        <dt>Obstacle area</dt><dd>{obstacle_area:.3} mm²</dd>
        <dt>Clearance-safe area</dt><dd>{clearance_safe_area:.3} mm²</dd>
        <dt>Regularized safe area</dt><dd>{safe_area:.3} mm²</dd>
        <dt>Removed area</dt><dd>{removed_area:.3} mm²</dd>
        <dt>Removed by opening</dt><dd>{removed_by_opening_area:.3} mm²</dd>
        <dt>Narrow voids</dt><dd>{narrow_void_area:.3} mm²</dd>
        <dt>Trimmed to widen gaps</dt><dd>{removed_by_gap_regularization_area:.3} mm²</dd>
        <dt>Retained</dt><dd>{retained_fraction:.1}%</dd>
        <dt>Safe fraction</dt><dd>{safe_fraction:.1}%</dd>
        <dt>Nominal clearance</dt><dd>{nominal_clearance:.3} mm</dd>
        <dt>Filled-region radius</dt><dd>{regularization_radius:.3} mm</dd>
        <dt>Void-gap radius</dt><dd>{gap_radius:.3} mm ({gap_width:.3} mm nominal gap)</dd>
        <dt>Geometry guard</dt><dd>{geometry_guard:.3} mm</dd>
        <dt>Regularization violations</dt><dd>{regularization_violation_area:.6} mm²</dd>
        <dt>Void-gap violations</dt><dd>{gap_violation_area:.6} mm²</dd>
        <dt>Components</dt><dd>{clearance_safe_components} → {opened_components} → {final_components}</dd>
        <dt>Smallest component</dt><dd>{smallest_component}</dd>
        <dt>Minimum component span</dt><dd>{minimum_component_span}</dd>
        <dt>Undersized components</dt><dd>{undersized_components}</dd>
        <dt>Panelizer</dt><dd>{panelizer}</dd>
        <dt>Board instances</dt><dd>{board_instances}</dd>
        <dt>Support features</dt><dd>{support_count}</dd>
        <dt>Excluded documentation paths</dt><dd>{excluded_documentation}</dd>
        <dt>Unpainted paths</dt><dd>{unpainted}</dd>
        <dt>Overall status</dt><dd class="{check_class}">{check_status}</dd>
      </dl>
      <details>
        <summary>Stage SVGs</summary>
        <ul>{stage_links}</ul>
      </details>
      <details>
        <summary>Non-empty support layers</summary>
        <ul>{support_links}</ul>
      </details>
    </aside>
    <section class="panel viewer">{overview}</section>
  </div>
</main>
<script>
  for (const checkbox of document.querySelectorAll('[data-layer]')) {{
    const apply = () => {{
      const target = document.getElementById(checkbox.dataset.layer);
      if (target) target.style.display = checkbox.checked ? '' : 'none';
    }};
    checkbox.addEventListener('change', apply);
    apply();
  }}
</script>
</body>
</html>
"#,
        title = escape_html(title),
        panel_outer = checked(true),
        panel_keep_in = checked(true),
        obstacle_keep_out = checked(false),
        clearance_safe_region = checked(false),
        opened_candidates = checked(false),
        removed_by_opening = checked(false),
        narrow_voids = checked(false),
        removed_by_gap_regularization = checked(true),
        safe_region = checked(true),
        board_footprints = checked(true),
        material_removal = checked(true),
        support_features = checked(true),
        certificate = checked(false),
        violations = checked(true),
        panel_area = regions.panel_outer.area(),
        copper_layer = escape_html(&artifact.copper_layer),
        obstacle_area = regions.raw_obstacles.area(),
        clearance_safe_area = artifact.regularization.clearance_safe_area_mm2,
        safe_area = regions.safe_region.area(),
        removed_area = artifact.regularization.removed_area_mm2,
        removed_by_opening_area = artifact.regularization.removed_by_opening_area_mm2,
        narrow_void_area = artifact.regularization.narrow_void_area_mm2,
        removed_by_gap_regularization_area = artifact
            .regularization
            .removed_by_gap_regularization_area_mm2,
        retained_fraction = 100.0 * artifact.regularization.retained_fraction,
        safe_fraction = 100.0 * regions.safe_region.area() / regions.panel_outer.area(),
        nominal_clearance = artifact.nominal_clearance_mm,
        regularization_radius = artifact.regularization_radius_mm,
        gap_radius = artifact.gap_radius_mm,
        gap_width = 2.0 * artifact.gap_radius_mm,
        geometry_guard = artifact.numerical_guard_mm,
        regularization_violation_area = artifact.checks.regularization_violation_area_mm2,
        gap_violation_area = artifact.checks.gap_violation_area_mm2,
        clearance_safe_components = artifact.regularization.clearance_safe_component_count,
        opened_components = artifact.regularization.opened_component_count,
        final_components = artifact.regularization.final_component_count,
        smallest_component = artifact
            .regularization
            .smallest_final_component_area_mm2
            .map(|area| format!("{area:.3} mm²"))
            .unwrap_or_else(|| "none".to_string()),
        minimum_component_span = artifact
            .regularization
            .minimum_final_component_bbox_span_mm
            .map(|span| format!("{span:.3} mm"))
            .unwrap_or_else(|| "none".to_string()),
        undersized_components = artifact.regularization.undersized_final_component_count,
        panelizer = escape_html(&format!(
            "{} {}",
            artifact.panelization.mode.as_deref().unwrap_or("unknown"),
            artifact.panelization.sheet.as_deref().unwrap_or("unsized")
        )),
        board_instances = artifact.counts.board_instances,
        support_count = artifact.counts.support_features,
        excluded_documentation = artifact.counts.excluded_documentation_paths,
        unpainted = artifact.coverage.unpainted_support_paths,
        check_class = if artifact.passed { "pass" } else { "fail" },
        check_status = if artifact.passed { "PASS" } else { "FAIL" },
    )
}

fn write_file(path: PathBuf, contents: &str) -> Result<()> {
    fs::write(&path, contents)
        .with_context(|| format!("failed to write debug artifact {}", path.display()))
}

fn slug(value: &str) -> String {
    let mut out = String::new();
    let mut separator = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            separator = false;
        } else if !separator && !out.is_empty() {
            out.push('-');
            separator = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    if out.is_empty() {
        "layer".to_string()
    } else {
        out
    }
}

fn num(value: f64) -> String {
    let mut value = if value.abs() < 5e-9 { 0.0 } else { value };
    if value == -0.0 {
        value = 0.0;
    }
    let mut text = format!("{value:.6}");
    while text.contains('.') && text.ends_with('0') {
        text.pop();
    }
    if text.ends_with('.') {
        text.pop();
    }
    text
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
